#!/bin/sh

if ./compilar \
    && echo "Comenzando ejecución..." \
    && sleep 1 \
    && ./Programa
then
  echo -e "\e[32mEjecución correcta.\e[0m"
else
  echo -e "\e[1;31mEjecución fallida.\e[0m"
fi