#!/bin/sh

tput reset
if ./Scripts/actualizar \
    && echo -e "\e[1mCompilando...\e[0m" \
    && ./Scripts/invocar_compilador
then
  echo -e "\e[32mCompilación correcta.\e[0m"
else
  echo -e "\e[91mCompilación fallida.\e[0m" && exit 1
fi