#!/bin/sh

if ./Scripts/compilar \
    && echo -e "\e[1mComenzando ejecución...\e[0m" \
    && sleep 1 \
    && ./Programa
then
  echo -e "\e[32mEjecución correcta.\e[0m"
else
  echo -e "\e[91mEjecución fallida.\e[0m" && exit 1
fi